import { LedgerDocument } from './types';

export const INITIAL_DOCUMENTS: LedgerDocument[] = [
  {
    id: 'doc-1025',
    vendor: 'ABC Traders',
    invoiceNumber: 'INV-1025',
    date: '10 Sep 2026',
    subtotal: 10000,
    taxGst: 1800,
    totalAmount: 11800,
    calculatedTotal: 11800,
    category: 'Office Equipment',
    status: 'Ready for Review',
    checks: {
      requiredInfoFound: true,
      amountVerified: true,
      noDuplicateFound: true,
    },
    issueDescription: null,
    items: [
      { description: 'Ergonomic Executive Desk Chair', quantity: 2, unitPrice: 4000, amount: 8000 },
      { description: 'Wireless Mechanical Keyboards', quantity: 2, unitPrice: 1000, amount: 2000 },
    ],
    uploadedAt: '2026-09-10T10:15:00Z',
    fileName: 'INV_1025_ABC_Traders.pdf',
    fileType: 'application/pdf',
  },
  {
    id: 'doc-1026',
    vendor: 'XYZ Supplies',
    invoiceNumber: 'INV-1026',
    date: '09 Sep 2026',
    subtotal: 10000,
    taxGst: 1800,
    totalAmount: 13000,
    calculatedTotal: 11800,
    category: 'Office Supplies',
    status: 'Needs Review',
    checks: {
      requiredInfoFound: true,
      amountVerified: false,
      noDuplicateFound: true,
    },
    issueDescription: 'Amount mismatch: Invoice total is ₹13,000 but line items + GST calculate to ₹11,800.',
    items: [
      { description: 'Heavy Duty Laser Printer Toner', quantity: 4, unitPrice: 2000, amount: 8000 },
      { description: 'A4 Premium Printing Paper (Box of 5)', quantity: 2, unitPrice: 1000, amount: 2000 },
    ],
    uploadedAt: '2026-09-09T14:30:00Z',
    fileName: 'INV_1026_XYZ_Supplies.pdf',
    fileType: 'application/pdf',
  },
  {
    id: 'doc-1035',
    vendor: 'OfficeMart',
    invoiceNumber: 'INV-1035',
    date: '08 Sep 2026',
    subtotal: 7203,
    taxGst: 1297,
    totalAmount: 8500,
    calculatedTotal: 8500,
    category: 'Supplies',
    status: 'Approved',
    checks: {
      requiredInfoFound: true,
      amountVerified: true,
      noDuplicateFound: true,
    },
    issueDescription: null,
    items: [
      { description: 'Stationery & Whiteboard Accessories', quantity: 1, unitPrice: 7203, amount: 7203 },
    ],
    uploadedAt: '2026-09-08T09:45:00Z',
    fileName: 'INV_1035_OfficeMart.pdf',
    fileType: 'application/pdf',
  },
  {
    id: 'doc-1036',
    vendor: 'Global Logistics Corp',
    invoiceNumber: 'INV-1036',
    date: '07 Sep 2026',
    subtotal: 14500,
    taxGst: 2610,
    totalAmount: 18000,
    calculatedTotal: 17110,
    category: 'Freight & Shipping',
    status: 'Needs Review',
    checks: {
      requiredInfoFound: true,
      amountVerified: false,
      noDuplicateFound: true,
    },
    issueDescription: 'Amount mismatch: Discrepancy of ₹890 between total and freight calculations.',
    items: [
      { description: 'Interstate Freight Courier Services', quantity: 1, unitPrice: 14500, amount: 14500 },
    ],
    uploadedAt: '2026-09-07T16:20:00Z',
    fileName: 'INV_1036_GlobalLogistics.pdf',
    fileType: 'application/pdf',
  },
  {
    id: 'doc-1037',
    vendor: 'CloudScale Technologies',
    invoiceNumber: 'INV-1037',
    date: '06 Sep 2026',
    subtotal: 25000,
    taxGst: 4500,
    totalAmount: 29500,
    calculatedTotal: 29500,
    category: 'Software & Cloud',
    status: 'Needs Review',
    checks: {
      requiredInfoFound: false,
      amountVerified: true,
      noDuplicateFound: true,
    },
    issueDescription: 'Missing information: Tax registration GSTIN number missing from vendor header.',
    items: [
      { description: 'Monthly Enterprise Infrastructure Hosting', quantity: 1, unitPrice: 25000, amount: 25000 },
    ],
    uploadedAt: '2026-09-06T11:10:00Z',
    fileName: 'INV_1037_CloudScale.pdf',
    fileType: 'application/pdf',
  },
  {
    id: 'doc-1038',
    vendor: 'Apex Caterers',
    invoiceNumber: 'INV-1038',
    date: '05 Sep 2026',
    subtotal: 12000,
    taxGst: 600,
    totalAmount: 13500,
    calculatedTotal: 12600,
    category: 'Meals & Hospitality',
    status: 'Needs Review',
    checks: {
      requiredInfoFound: true,
      amountVerified: false,
      noDuplicateFound: true,
    },
    issueDescription: 'Amount mismatch: Total charge ₹13,500 exceeds calculated total ₹12,600.',
    items: [
      { description: 'Corporate Team Luncheon Catering', quantity: 40, unitPrice: 300, amount: 12000 },
    ],
    uploadedAt: '2026-09-05T13:00:00Z',
    fileName: 'INV_1038_ApexCatering.pdf',
    fileType: 'application/pdf',
  },
  // Additional approved historical records to total 24 documents
  ...Array.from({ length: 18 }).map((_, idx) => ({
    id: `doc-${1000 + idx}`,
    vendor: [
      'TechCraft Systems', 'Metro Stationers', 'FastTrack Logistics', 'Zenith Design Studio',
      'Reliable Telecom', 'Summit Cleaners', 'Urban Office Goods', 'Bright Spark Electric',
      'Prime Security Solutions', 'NextGen Softworks', 'Horizon Freight', 'Apex Hardware'
    ][idx % 12],
    invoiceNumber: `INV-${1000 + idx}`,
    date: `${Math.max(1, 30 - idx)} Aug 2026`,
    subtotal: (idx + 1) * 3500,
    taxGst: Math.round((idx + 1) * 3500 * 0.18),
    totalAmount: Math.round((idx + 1) * 3500 * 1.18),
    calculatedTotal: Math.round((idx + 1) * 3500 * 1.18),
    category: ['Office Equipment', 'Supplies', 'Utilities', 'Professional Services', 'Software & Cloud'][idx % 5],
    status: 'Approved' as const,
    checks: {
      requiredInfoFound: true,
      amountVerified: true,
      noDuplicateFound: true,
    },
    issueDescription: null,
    items: [
      { description: 'Accounting Operations & Supplies', quantity: 1, unitPrice: (idx + 1) * 3500, amount: (idx + 1) * 3500 }
    ],
    uploadedAt: `2026-08-${String(Math.max(1, 30 - idx)).padStart(2, '0')}T10:00:00Z`,
    fileName: `INV_${1000 + idx}_Record.pdf`,
    fileType: 'application/pdf',
  }))
];
